version: '3'

services:
  tarkov-cron:
    container_name: tarkov-cron
    build: .
    environment:
      NODE_ENV: production
      CLOUDFLARE_TOKEN: ${CLOUDFLARE_TOKEN}
      PSCALE_USER: ${PSCALE_USER}
      PSCALE_PASS: ${PSCALE_PASS}
      WEBHOOK_URL: ${WEBHOOK_URL}
      WEBHOOK_USER: tarkov-cron-alert
      DATABASE_NAME: tarkov
      DATABASE_HOST: 6hvetf6kcr04.us-east-1.psdb.cloud
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BSG_BASE_PRICE_URL: https://gist.githubusercontent.com/austinhodak/e5ba6130583fe07a890c1e70d55b776c/raw/2ffea26a4a1e6e2275e0d804da96218e946c75dd/base_prices.json
      BSG_DATA_URL: https://gist.githubusercontent.com/austinhodak/e5ba6130583fe07a890c1e70d55b776c/raw/ad6e370b7ae26a5a14a73fbf2f95c170890b64bf/item_data.json
      BSG_TRANSLATIONS_URL: https://gist.githubusercontent.com/austinhodak/e5ba6130583fe07a890c1e70d55b776c/raw/e7fc0839a592f210234a9c3956a7d751edb06a13/translations.json
      MONGODB_URL: ${MONGODB_URL}

    command: "${TARKOV_CRON}"
