version: '3'

services:
  tarkov-cron:
    container_name: tarkov-cron
    build: .
    environment:
      NODE_ENV: production
      CLOUDFLARE_TOKEN: ${CLOUDFLARE_TOKEN}
      MYSQL_USERNAME: ${PSCALE_USER}
      MYSQL_PASSWORD: ${PSCALE_PASS}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BSG_BASE_PRICE_URL: https://gist.githubusercontent.com/austinhodak/e5ba6130583fe07a890c1e70d55b776c/raw/ad6e370b7ae26a5a14a73fbf2f95c170890b64bf/base_prices.json
      BSG_DATA_URL: https://gist.githubusercontent.com/austinhodak/e5ba6130583fe07a890c1e70d55b776c/raw/ad6e370b7ae26a5a14a73fbf2f95c170890b64bf/item_data.json
      BSG_TRANSLATIONS_URL: https://gist.githubusercontent.com/austinhodak/e5ba6130583fe07a890c1e70d55b776c/raw/e7fc0839a592f210234a9c3956a7d751edb06a13/translations.json

    command: "${TARKOV_CRON}"
