version: '3'

services:
  tarkov-cron:
    container_name: tarkov-cron
    build: .
    environment:
      NODE_ENV: production
      CLOUDFLARE_TOKEN: ${CLOUDFLARE_TOKEN}
      PSCALE_USER: ${PSCALE_USER}
      PSCALE_PASS: ${PSCALE_PASS}
      WEBHOOK_URL: ${WEBHOOK_URL}
      WEBHOOK_USER: tarkov-cron-alert
      DATABASE_NAME: tarkov
      DATABASE_HOST: 6hvetf6kcr04.us-east-1.psdb.cloud
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BSG_BASE_PRICE_URL: https://raw.githubusercontent.com/austinhodak/tarkov-raw/master/base_prices.json
      BSG_DATA_URL: https://raw.githubusercontent.com/austinhodak/tarkov-raw/master/item_data.json
      BSG_TRANSLATIONS_URL: https://raw.githubusercontent.com/austinhodak/tarkov-raw/master/translations_en.json
      MONGODB_URL: ${MONGODB_URL}

    command: "${TARKOV_CRON}"
