name: update-hideout

on:
  push:
      branches: [ main ]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-hideout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update-hideout
        run: |
          docker-compose up --build
          [ $? -eq 0 ] && exit 0 || exit 1
        env:
          TARKOV_CRON: update-hideout
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          MYSQL_USERNAME: ${{ secrets.PSCALE_USER }}
          MYSQL_PASSWORD: ${{ secrets.PSCALE_PASS }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
